server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss}- %msg%n"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**

        - id: children-service
          uri: lb://children-service
          predicates:
            - Path=/children/**
          filters:
            - AuthenticationFilter
#           надо зайти в этот класс. где то-взять JWT токен. и пришить ко всем запросам Header Key Value с токеном

        - id: training-service
          uri: lb://training-service
          predicates:
            - Path=/training/**
          filters:
            - AuthenticationFilter
