spring:
 cloud:
   gateway:
     routes:
#       - id: identity-service
#         uri: lb://identity-service
#         predicates:
#           - Path=/identity/**
#         filters:
#           - AuthenticationFilter

       - id: keycloack-server
         uri: lb://keycloack-server
         predicates:
           - Path=/auth/**

       - id: children-service
         uri: lb://children-service
         predicates:
           - Path=/children/**

       - id: training-service
         uri: lb://training-service
         predicates:
           - Path=/training/**


#       - id: guru-identity-service
#         uri: lb://guru-identity-service
#         predicates:
#           - Path=/auth/**

 application:
   name: JAVAGURU-GATEWAY
 security:
   oauth2:
     resourceserver:
       jwt:
         issuer-uri: http://localhost:8080/realms/user-realm

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss}- %msg%n"

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/